import type { Metadata } from "next";
import Header from "@/component/header";
import "@/pages/_app";
import { Inter } from "next/font/google";
import Footer from "@/component/Footer";
import Adventage from "@/component/Adventage";

const inter = Inter({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "ASAXIY internet do'koni ",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://asaxiy.uz/custom-assets/images/logos/l-b.svg" />
        <meta name="description" content="Asaxiy internet do'koni - kitoblar, elektronika, maishiy texnika va boshqalar ✔️ O'zbekiston bo'ylab tez yetkazib berish ⭐Arzon narxlar ☝ Keng assortiment ⚡ Chegirmalar ⌚ Bo'lib to'lash"></meta>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Adventage />
        <Footer />
      </body>
    </html>
  );
}
