import type { Metadata } from "next";
import Header from "@/component/header";
import "@/pages/_app"
import {Inter} from "next/font/google"
import Footer from "@/component/Footer";
import Adventage from "@/component/Adventage";

const inter = Inter({subsets: ['latin'], weight: '400'})
export const metadata: Metadata = {
  title: "Asaxiy uz",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Adventage/>
        <Footer/>
      </body>
    </html>
  );
}
