import type { Metadata } from "next";
import Home from "./home/page";
import Header from "@/component/header";
import "@/pages/_app"

export const metadata: Metadata = {
  title: "Asaxiy uz",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Home/>
      </body>
    </html>
  );
}
